#!/bin/bash

# this script runs build according to documentation
# at https://allseenalliance.org/framework/documentation/develop/building/thin-linux

# make sure to run ./setup first time before building

platform=${PLATFORM:-`uname -i`}   # platform: x86_64|armhf
variant=${VARIANT:-"release"}      # variant: debug|release
# echo "platform=$platform variant=$variant"

case $platform in
    arm|armhf|RPi|RPi2)
        cross_compile=arm-linux-gnueabihf-
        cpu=armhf
        ;;

    *)
        cross_compile=
        cpu=$platform
        ;;
esac

# build standard core
pushd ./core/alljoyn
scons BINDINGS=cpp WS=off BT=off ICE=off VARIANT=$variant CROSS_COMPILE=$cross_compile CPU=$cpu || exit 1
#SERVICES="about,notification,controlpanel,config,onboarding,sample_apps"
popd

# build thin core
pushd ./core/ajtcl
CROSS_PREFIX=$cross_compile CROSS_CFLAGS="" CROSS_LINKFLAGS="" scons -c BINDINGS=cpp WS=off VARIANT=$variant # need to clean all intermediate builds!
CROSS_PREFIX=$cross_compile CROSS_CFLAGS="" CROSS_LINKFLAGS="" scons BINDINGS=cpp WS=off VARIANT=$variant || exit 1
popd

exit 0 # OK

