#!/bin/bash

# this script executes setup steps according to ifficial documentation
# at https://allseenalliance.org/framework/documentation/develop/building

# Build tools and libs
sudo apt-get install build-essential libgtk2.0-dev  libcap-dev libssl-dev xsltproc ia32-libs libxml2-dev
sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf # required for cross compilation

# Install Python v2.6/2.7 (Python v3.0 is not compatible and will cause errors)
sudo apt-get install python

# Installl SCons v2.0.
sudo apt-get install scons

#cOpenSSL
sudo apt-get install libssl-dev

