#!/bin/bash

# this script executes setup steps according to ifficial documentation
# at https://allseenalliance.org/framework/documentation/develop/building

# Build tools and libs
sudo apt-get install build-essential libgtk2.0-dev  libcap-dev libssl-dev xsltproc ia32-libs libxml2-dev
sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf # required for cross compilation

# Install Python v2.6/2.7 (Python v3.0 is not compatible and will cause errors)
sudo apt-get install python

# Installl SCons v2.0.
sudo apt-get install scons

# OpenSSL
sudo apt-get install libssl-dev

# OpenSSL (ARM)
OPENSSL=openssl-1.0.0q
[ -e $OPENSSL.tar.gz ] || wget https://www.openssl.org/source/$OPENSSL.tar.gz
[ -d $OPENSSL ] || tar xvf $OPENSSL.tar.gz
pushd $OPENSSL
export cross=arm-linux-gnueabihf-
./Configure dist --prefix=/usr/arm-linux-gnueabihf -fPIC shared
make CC="${cross}gcc" AR="${cross}ar r" RANLIB="${cross}ranlib"
sudo make install
popd

